# Generated by Django 2.2.10 on 2021-01-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('image1', models.ImageField(null=True, upload_to='blogs/')),
                ('first_paragraph', models.TextField()),
                ('image2', models.ImageField(null=True, upload_to='blogs/')),
                ('second_paragraph', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('read_time', models.IntegerField()),
                ('homepage_display', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='casrousal/')),
                ('heading', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='events/')),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('C', 'Completed'), ('U', 'Upcomming')], default='O', max_length=5)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='gallery/')),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
