# Generated by Django 3.1.4 on 2021-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousal',
            name='description',
        ),
        migrations.AlterField(
            model_name='carousal',
            name='heading',
            field=models.CharField(max_length=150),
        ),
    ]
