# Generated by Django 2.2.10 on 2021-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210110_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustteammember',
            name='designation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
