# Generated by Django 3.1.4 on 2021-01-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210106_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='first_paragraph',
        ),
        migrations.AddField(
            model_name='blog',
            name='second_paragraph',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
